// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_application_1/classes/person.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PersonAdapter());
  }
}
